### ISSUE TITLE
Error when hotswapping CSS file name

### ISSUE THREAD

**Issue by DonyorM** [halgari/fn-fx#20]
I have a setup where the name of my .css file is stored in the data-state atom. I tried using the method suggested by [this](http://nils-blum-oeste.net/javafx-style-using-clojure-fn-fx-garden-desktop-application-design/) blog post on how to dynamically update the style on the repl. However, about 50% of the time when I set the css file to a new string (with `(swap! data-state assoc-in [:ui :stylesheets] ["main.css"])`) the below error occurs. Even if the error doesn't occur, the window does not update its style. At the very least, I imagine the error message should be improved.

```
#error {
 :cause Assert failed: TODO: Implement this
(= idx (count lst))
 :via
 [{:type java.lang.AssertionError
   :message Assert failed: TODO: Implement this
(= idx (count lst))
   :at [fn_fx.fx_dom.FXDom$fn__18087 invoke fx_dom.clj 33]}]
 :trace
 [[fn_fx.fx_dom.FXDom$fn__18087 invoke fx_dom.clj 33]
  [clojure.lang.AFn run AFn.java 22]
  [com.sun.javafx.application.PlatformImpl lambda$null$173 PlatformImpl.java 295]
  [java.security.AccessController doPrivileged AccessController.java -2]
  [com.sun.javafx.application.PlatformImpl lambda$runLater$174 PlatformImpl.java 294]
  [com.sun.glass.ui.InvokeLaterDispatcher$Future run InvokeLaterDispatcher.java 95]
  [com.sun.glass.ui.gtk.GtkApplication _runLoop GtkApplication.java -2]
  [com.sun.glass.ui.gtk.GtkApplication lambda$null$49 GtkApplication.java 139]
  [java.lang.Thread run Thread.java 745]]}
 "Elapsed time: 3.601076 msecs"
```

**Comment by nblumoe** [comment]
Hey, this should be solved by  using the latest fn-fx version. Which is not yet on Clojars though, you need to install it for example via `lein install` from a checked out repo. 
-------- Original message --------From: Daniel Manila <notifications@github.com> Date: 7/25/17  06:57  (GMT+01:00) To: halgari/fn-fx <fn-fx@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [halgari/fn-fx] Error when hotswapping CSS file name (#20) 
I have a setup where the name of my .css file is stored in the data-state atom. I tried using the method suggested by this blog post on how to dynamically update the style on the repl. However, about 50% of the time when I set the css file to a new string (with (swap! data-state assoc-in [:ui :stylesheets] ["main.css"])) the below error occurs. Even if the error doesn't occur, the window does not update its style. At the very least, I imagine the error message should be improved.
#error {
 :cause Assert failed: TODO: Implement this
(= idx (count lst))
 :via
 [{:type java.lang.AssertionError
   :message Assert failed: TODO: Implement this
(= idx (count lst))
   :at [fn_fx.fx_dom.FXDom$fn__18087 invoke fx_dom.clj 33]}]
 :trace
 [[fn_fx.fx_dom.FXDom$fn__18087 invoke fx_dom.clj 33]
  [clojure.lang.AFn run AFn.java 22]
  [com.sun.javafx.application.PlatformImpl lambda$null$173 PlatformImpl.java 295]
  [java.security.AccessController doPrivileged AccessController.java -2]
  [com.sun.javafx.application.PlatformImpl lambda$runLater$174 PlatformImpl.java 294]
  [com.sun.glass.ui.InvokeLaterDispatcher$Future run InvokeLaterDispatcher.java 95]
  [com.sun.glass.ui.gtk.GtkApplication _runLoop GtkApplication.java -2]
  [com.sun.glass.ui.gtk.GtkApplication lambda$null$49 GtkApplication.java 139]
  [java.lang.Thread run Thread.java 745]]}
 "Elapsed time: 3.601076 msecs"


—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/halgari/fn-fx","title":"halgari/fn-fx","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/halgari/fn-fx"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Error when hotswapping CSS file name (#20)"}],"action":{"name":"View Issue","url":"https://github.com/halgari/fn-fx/issues/20"}}}

**Comment by DonyorM** [comment]
That worked. Thanks for your help.
